const {test} = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const os = require('node:os')
const {once} = require('node:events')
const {createPublicationServer} = require('../publication/interfaces/server.cjs')
const {FilePublicationRepository} = require('../publication/infrastructure/FilePublicationRepository.cjs')
const {PublicationCoordinator} = require('../publication/application/PublicationCoordinator.cjs')

test('private publication controls require credentials; public pages read only the committed release', async () => {
    const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'publication-http-test-'))
    const repository = new FilePublicationRepository(directory)
    const coordinator = new PublicationCoordinator({repository, source: {}, renderer: {}})
    const token = 'fixture-secret-not-a-real-credential'
    const server = createPublicationServer({repository, coordinator, directory, token})
    try {
        await fs.mkdir(path.join(directory, 'releases/release-old/article/11'), {recursive: true})
        await fs.writeFile(path.join(directory, 'releases/release-old/article/11/index.html'), '<!doctype html><body>已发布页面</body>')
        await repository.save({...await repository.load(), phase: 'FAILED', activeRelease: 'release-old'})
        server.listen(0, '127.0.0.1'); await once(server, 'listening')
        const base = `http://127.0.0.1:${server.address().port}`
        assert.equal((await fetch(base + '/internal/status')).status, 401)
        assert.equal((await fetch(base + '/internal/retry', {method: 'POST'})).status, 401)
        const status = await fetch(base + '/internal/status', {headers: {'X-Publication-Key': token}})
        assert.equal(status.status, 200)
        assert.equal((await status.json()).phase, 'FAILED')
        const page = await fetch(base + '/blog/article/11/')
        assert.equal(page.status, 200)
        assert.match(await page.text(), /已发布页面/)
        assert.equal(page.headers.get('cache-control'), 'no-store')
        for (const url of ['/publication.json', '/blog/%2e%2e/publication.json', '/blog/article/12/'])
            assert.equal((await fetch(base + url)).status, 404)
        assert.equal((await fetch(base + '/internal/retry', {method: 'POST', headers: {'X-Publication-Key': token, Origin: 'https://untrusted.example'}})).status, 403)
        const retry = await fetch(base + '/internal/retry', {method: 'POST', headers: {'X-Publication-Key': token}})
        assert.equal(retry.status, 202)
        assert.equal((await retry.json()).phase, 'WAITING')
    } finally {
        if (server.listening) await new Promise(resolve => server.close(resolve))
        assert.equal(path.dirname(directory), os.tmpdir())
        assert.match(path.basename(directory), /^publication-http-test-/)
        await fs.rm(directory, {recursive: true, force: true})
    }
})
