import test from 'node:test'
import assert from 'node:assert/strict'
import {parseDump, renderPostgres} from './mysql-dump.mjs'

const sample = String.raw`
-- Fixture only, no real user data.
/*!40101 SET NAMES utf8mb4 */;
DROP TABLE IF EXISTS \`article\`;
CREATE TABLE \`article\` (
  \`id\` bigint NOT NULL AUTO_INCREMENT,
  \`title\` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  \`content_md\` longtext NOT NULL,
  \`status\` tinyint NOT NULL DEFAULT '0',
  \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`) USING BTREE,
  UNIQUE KEY \`uk_title\` (\`title\`) USING BTREE,
  KEY \`idx_status\` (\`status\`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4;
LOCK TABLES \`article\` WRITE;
INSERT INTO \`article\` VALUES (7,'中文; quote\' and ''double''','<p>a\\b\nline</p> /*! keep this */',1,'2026-09-22 12:30:00');
UNLOCK TABLES;
`.replaceAll('\\`', '`')

test('parses a dump without executing directives or leaking data', () => {
    const dump = parseDump(sample)
    assert.equal(dump.tables.length, 1)
    assert.equal(dump.tables[0].rows.length, 1)
    assert.equal(dump.tables[0].rows[0][1], "中文; quote' and 'double'")
    assert.equal(dump.tables[0].rows[0][2], '<p>a\\b\nline</p> /*! keep this */')
    assert.equal(dump.tables[0].nextId, '25')
})

test('renders identity, numeric flags, update trigger and indexes safely', () => {
    const {sql, report} = renderPostgres(parseDump(sample))
    assert.match(sql, /GENERATED BY DEFAULT AS IDENTITY/)
    assert.match(sql, /"status" smallint/)
    assert.match(sql, /timestamp without time zone/i)
    assert.match(sql, /CREATE TRIGGER/)
    assert.match(sql, /CREATE UNIQUE INDEX "uk_title".*lower\("title"\)/)
    assert.match(sql, /setval\(.*25.*false/s)
    assert.match(sql, /quote'' and ''double''/)
    assert.match(sql, /requires an empty target schema/)
    assert.match(sql, /BEGIN;/)
    assert.match(sql, /COMMIT;/)
    assert.doesNotMatch(sql, /DROP TABLE|INSERT IGNORE|AUTO_INCREMENT|ENGINE=|LOCK TABLES/)
    assert.deepEqual(report.tables.map(t => [t.name, t.rows]), [['article', 1]])
    assert.ok(!JSON.stringify(report).includes('quote'))
})

test('rejects unsupported SQL instead of silently dropping it', () => {
    assert.throws(() => parseDump(sample + '\nCREATE PROCEDURE unsafe() SELECT 1;'), /Unsupported statement/)
    assert.throws(() => parseDump(sample.replace("'2026-09-22 12:30:00'", 'NOW()')), /Unsupported value/)
    assert.throws(() => parseDump(sample.replace('longtext NOT NULL', 'blob NOT NULL')), /Unsupported column/)
})

test('validates row width and refuses malformed, truncated strings', () => {
    assert.throws(() => parseDump(sample.replace(",1,'2026-09-22 12:30:00'", ",1")), /Column count/)
    assert.throws(() => parseDump("INSERT INTO `article` VALUES (1,'unfinished"), /Unterminated/)
    assert.throws(() => parseDump(sample.replace('a\\\\b\\nline', 'a\\0b')), /NUL/)
})

test('schema-only output contains no private rows or snapshot sequence offsets', () => {
    const {sql} = renderPostgres(parseDump(sample), {schemaOnly: true})
    assert.doesNotMatch(sql, /INSERT INTO|setval\(|quote|GREATEST\(/)
    assert.match(sql, /CREATE TABLE "article"/)
})

test('preserves IDs above Number.MAX_SAFE_INTEGER, nulls and SQL-looking content', () => {
    const changed = sample.replace("(7,'中文;", "(9007199254740993,'中文;")
    assert.equal(parseDump(changed).tables[0].rows[0][0], '9007199254740993')
    assert.throws(() => parseDump(sample + sample), /Duplicate table/)
})
