-- Generated by tools/database/convert-mysql-dump.mjs. No original SQL is executed.
-- Source SHA-256: 857043315210082caf8226b73d83db6f1ed229b8527b3705874c0a82f8819594
-- Requires an EMPTY public schema. Never overwrite an existing database.
BEGIN;
SET LOCAL search_path = public;
SET LOCAL lock_timeout = '5s';
SET LOCAL standard_conforming_strings = on;
DO
$guard$
BEGIN IF
EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m','S','f')) THEN RAISE EXCEPTION 'Migration requires an empty target schema';
END IF;
END $guard$;
CREATE FUNCTION blog_touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS $touch$
BEGIN
  IF
NEW IS DISTINCT FROM OLD AND NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
    NEW.updated_at := statement_timestamp();
END IF;
RETURN NEW;
END
$touch$;
CREATE TABLE "article"
(
    "id"                 bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "author_id"          bigint                                  NOT NULL,
    "title"              varchar(200)                            NOT NULL,
    "summary"            varchar(500)                                     DEFAULT NULL,
    "content_md"         text                                    NOT NULL,
    "content_html"       text,
    "cover_url"          varchar(255)                                     DEFAULT NULL,
    "category_id"        bigint                                           DEFAULT NULL,
    "status"             smallint                                NOT NULL DEFAULT '0',
    "is_top"             smallint                                NOT NULL DEFAULT '0',
    "is_comment_enabled" smallint                                NOT NULL DEFAULT '1',
    "view_count"         integer                                 NOT NULL DEFAULT '0',
    "like_count"         integer                                 NOT NULL DEFAULT '0',
    "collect_count"      integer                                 NOT NULL DEFAULT '0',
    "publish_time"       timestamp without time zone DEFAULT NULL,
    "created_at"         timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"         timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"            smallint                                NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);
CREATE INDEX "idx_article_category_id" ON "article" ("category_id");
CREATE INDEX "idx_article_status" ON "article" ("status");
CREATE INDEX "idx_article_publish_time" ON "article" ("publish_time");
CREATE INDEX "idx_article_is_top" ON "article" ("is_top");
CREATE TRIGGER "touch_article"
    BEFORE UPDATE
    ON "article"
    FOR EACH ROW EXECUTE FUNCTION blog_touch_updated_at();
CREATE TABLE "article_like"
(
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "article_id" bigint                                  NOT NULL,
    "user_id"    bigint                                  NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_article_user" ON "article_like" ("article_id", "user_id");
CREATE TABLE "article_tag"
(
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "article_id" bigint                                  NOT NULL,
    "tag_id"     bigint                                  NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_article_tag" ON "article_tag" ("article_id", "tag_id");
CREATE TABLE "category"
(
    "id"          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name"        varchar(50)                             NOT NULL,
    "slug"        varchar(100)                            NOT NULL,
    "description" varchar(255)                                     DEFAULT NULL,
    "sort"        integer                                 NOT NULL DEFAULT '0',
    "status"      smallint                                NOT NULL DEFAULT '1',
    "created_at"  timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     smallint                                NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_category_slug" ON "category" (lower("slug"));
CREATE TRIGGER "touch_category"
    BEFORE UPDATE
    ON "category"
    FOR EACH ROW EXECUTE FUNCTION blog_touch_updated_at();
CREATE TABLE "comment"
(
    "id"               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "article_id"       bigint                                  NOT NULL,
    "user_id"          bigint                                  NOT NULL,
    "parent_id"        bigint                                  NOT NULL DEFAULT '0',
    "reply_to_user_id" bigint                                           DEFAULT NULL,
    "content"          varchar(1000)                           NOT NULL,
    "status"           smallint                                NOT NULL DEFAULT '1',
    "ip"               varchar(50)                                      DEFAULT NULL,
    "user_agent"       varchar(500)                                     DEFAULT NULL,
    "created_at"       timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"       timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"          smallint                                NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);
CREATE INDEX "idx_comment_article_id" ON "comment" ("article_id");
CREATE INDEX "idx_comment_parent_id" ON "comment" ("parent_id");
CREATE TRIGGER "touch_comment"
    BEFORE UPDATE
    ON "comment"
    FOR EACH ROW EXECUTE FUNCTION blog_touch_updated_at();
CREATE TABLE "login_log"
(
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id"      bigint                                           DEFAULT NULL,
    "username"     varchar(50)                                      DEFAULT NULL,
    "login_status" smallint                                NOT NULL DEFAULT '1',
    "login_type"   varchar(20)                             NOT NULL DEFAULT 'phone',
    "ip"           varchar(50)                                      DEFAULT NULL,
    "user_agent"   varchar(500)                                     DEFAULT NULL,
    "fail_reason"  varchar(255)                                     DEFAULT NULL,
    "created_at"   timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);
CREATE INDEX "idx_login_user" ON "login_log" ("user_id");
CREATE INDEX "idx_login_created" ON "login_log" ("created_at");
CREATE TABLE "operation_log"
(
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id"      bigint       DEFAULT NULL,
    "module"       varchar(50)                             NOT NULL,
    "action"       varchar(100)                            NOT NULL,
    "content"      varchar(500) DEFAULT NULL,
    "request_data" text,
    "ip"           varchar(50)  DEFAULT NULL,
    "user_agent"   varchar(500) DEFAULT NULL,
    "created_at"   timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);
CREATE INDEX "idx_operation_module" ON "operation_log" ("module");
CREATE INDEX "idx_operation_user" ON "operation_log" ("user_id");
CREATE INDEX "idx_operation_created" ON "operation_log" ("created_at");
CREATE TABLE "sys_permission"
(
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "perm_code"  varchar(100)                            NOT NULL,
    "perm_name"  varchar(100)                            NOT NULL,
    "perm_type"  varchar(20)                             NOT NULL,
    "parent_id"  bigint                                           DEFAULT '0',
    "path"       varchar(255)                                     DEFAULT NULL,
    "component"  varchar(255)                                     DEFAULT NULL,
    "icon"       varchar(100)                                     DEFAULT NULL,
    "sort"       integer                                 NOT NULL DEFAULT '0',
    "status"     smallint                                NOT NULL DEFAULT '1',
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_sys_perm_code" ON "sys_permission" (lower("perm_code"));
CREATE TRIGGER "touch_sys_permission"
    BEFORE UPDATE
    ON "sys_permission"
    FOR EACH ROW EXECUTE FUNCTION blog_touch_updated_at();
CREATE TABLE "sys_role"
(
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "role_code"  varchar(50)                             NOT NULL,
    "role_name"  varchar(50)                             NOT NULL,
    "status"     smallint                                NOT NULL DEFAULT '1',
    "remark"     varchar(255)                                     DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"    smallint                                NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_sys_role_code" ON "sys_role" (lower("role_code"));
CREATE TRIGGER "touch_sys_role"
    BEFORE UPDATE
    ON "sys_role"
    FOR EACH ROW EXECUTE FUNCTION blog_touch_updated_at();
CREATE TABLE "sys_role_permission"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "role_id"       bigint                                  NOT NULL,
    "permission_id" bigint                                  NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_role_perm" ON "sys_role_permission" ("role_id", "permission_id");
CREATE TABLE "sys_user"
(
    "id"              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "phone"           varchar(20)                             NOT NULL,
    "username"        varchar(50)                             NOT NULL,
    "password"        varchar(255)                            NOT NULL,
    "nickname"        varchar(50)                                      DEFAULT NULL,
    "avatar"          varchar(255)                                     DEFAULT NULL,
    "email"           varchar(100)                                     DEFAULT NULL,
    "status"          smallint                                NOT NULL DEFAULT '1',
    "last_login_time" timestamp without time zone DEFAULT NULL,
    "created_at"      timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"      timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"         smallint                                NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_sys_user_phone" ON "sys_user" (lower("phone"));
CREATE UNIQUE INDEX "uk_sys_user_username" ON "sys_user" (lower("username"));
CREATE INDEX "idx_sys_user_email" ON "sys_user" ("email");
CREATE TRIGGER "touch_sys_user"
    BEFORE UPDATE
    ON "sys_user"
    FOR EACH ROW EXECUTE FUNCTION blog_touch_updated_at();
CREATE TABLE "sys_user_role"
(
    "id"      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" bigint                                  NOT NULL,
    "role_id" bigint                                  NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_user_role" ON "sys_user_role" ("user_id", "role_id");
CREATE TABLE "tag"
(
    "id"         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name"       varchar(50)                             NOT NULL,
    "slug"       varchar(100)                            NOT NULL,
    "color"      varchar(20)                                      DEFAULT NULL,
    "sort"       integer                                 NOT NULL DEFAULT '0',
    "status"     smallint                                NOT NULL DEFAULT '1',
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"    smallint                                NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "uk_tag_slug" ON "tag" (lower("slug"));
CREATE TRIGGER "touch_tag"
    BEFORE UPDATE
    ON "tag"
    FOR EACH ROW EXECUTE FUNCTION blog_touch_updated_at();
COMMIT;
